name: Homebrew Livecheck

on:
  schedule:
  - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  livecheck:
    runs-on: macos-latest
    
    steps: 
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Update Homebrew Formula
      uses: dawidd6/action-homebrew-bump-formula@v3
      with:
        token: ${{ secrets.HOMEBREW_TOKEN }}
        tap: nepherte/roon
        livecheck: true
